"""add families

Family members (patients) now belong to a family owned by one user, replacing the
per-patient `user_patient_access` table (CLAUDE.md Section 4.5).

Autogenerated from app.models, then rewritten by hand: existing patients are moved into a
"My family" owned by their (earliest) owner before `family_id` becomes required and the
old access table is dropped. The downgrade rebuilds owner access rows from family
ownership; family names are lost and former viewer rows are not restored.

Revision ID: fd63c4d93886
Revises: 5eefbab520ce
Create Date: 2026-09-24 22:13:27.649700

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd63c4d93886"
down_revision: str | Sequence[str] | None = "5eefbab520ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Note: plain-string SQL in op.execute() must not contain ":" (bind-parameter syntax).


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "families",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_families_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_families")),
        sa.UniqueConstraint("owner_id", "name", name=op.f("uq_families_owner_id_name")),
    )
    op.add_column("patients", sa.Column("family_id", sa.Uuid(), nullable=True))

    # Move existing patients into one "My family" per owning user.
    op.execute(
        """
        INSERT INTO families (id, owner_id, name)
        SELECT gen_random_uuid(), owners.user_id, 'My family'
        FROM (SELECT DISTINCT user_id FROM user_patient_access WHERE role = 'owner') AS owners
        """
    )
    op.execute(
        """
        UPDATE patients
        SET family_id = families.id
        FROM (
            SELECT DISTINCT ON (patient_id) patient_id, user_id
            FROM user_patient_access
            WHERE role = 'owner'
            ORDER BY patient_id, created_at
        ) AS first_owner
        JOIN families
            ON families.owner_id = first_owner.user_id AND families.name = 'My family'
        WHERE patients.id = first_owner.patient_id
        """
    )
    # A patient without an owner could never be seen again; stop rather than drop it.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM patients WHERE family_id IS NULL) THEN
                RAISE EXCEPTION 'Some patients have no owner and cannot be put in a family';
            END IF;
        END
        $$
        """
    )

    op.alter_column("patients", "family_id", nullable=False)
    op.create_index(op.f("ix_patients_family_id"), "patients", ["family_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_patients_family_id_families"),
        "patients",
        "families",
        ["family_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_user_patient_access_patient_id"), table_name="user_patient_access")
    op.drop_table("user_patient_access")


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table(
        "user_patient_access",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'viewer')", name=op.f("ck_user_patient_access_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_user_patient_access_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_patient_access_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "patient_id", name=op.f("pk_user_patient_access")),
    )
    op.create_index(
        op.f("ix_user_patient_access_patient_id"),
        "user_patient_access",
        ["patient_id"],
        unique=False,
    )
    op.execute(
        """
        INSERT INTO user_patient_access (user_id, patient_id, role)
        SELECT families.owner_id, patients.id, 'owner'
        FROM patients
        JOIN families ON families.id = patients.family_id
        """
    )

    op.drop_constraint(op.f("fk_patients_family_id_families"), "patients", type_="foreignkey")
    op.drop_index(op.f("ix_patients_family_id"), table_name="patients")
    op.drop_column("patients", "family_id")
    op.drop_table("families")
