"""create core schema

Autogenerated from app.models, then edited by hand to enable the pgvector
extension first on upgrade and drop it last on downgrade.

Revision ID: 5eefbab520ce
Revises:
Create Date: 2026-09-24 21:02:30.396765

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5eefbab520ce"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "metric_dictionary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("canonical_unit", sa.Text(), nullable=False),
        sa.Column("aliases", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("loinc_code", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_dictionary")),
        sa.UniqueConstraint("canonical_name", name=op.f("uq_metric_dictionary_canonical_name")),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("sex", sa.Text(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sex IN ('male', 'female')", name=op.f("ck_patients_sex_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("lab_name", sa.Text(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_sha256", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="processing", nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("raw_extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_reports_file_sha256_hex")
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'pending_review', 'confirmed', 'failed')",
            name=op.f("ck_reports_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_reports_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("id", "patient_id", name=op.f("uq_reports_id_patient_id")),
        sa.UniqueConstraint(
            "patient_id", "file_sha256", name=op.f("uq_reports_patient_id_file_sha256")
        ),
    )
    op.create_index(
        "ix_reports_patient_id_collected_at",
        "reports",
        ["patient_id", "collected_at"],
        unique=False,
    )
    op.create_table(
        "user_patient_access",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'viewer')", name=op.f("ck_user_patient_access_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_user_patient_access_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_patient_access_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "patient_id", name=op.f("pk_user_patient_access")),
    )
    op.create_index(
        op.f("ix_user_patient_access_patient_id"),
        "user_patient_access",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_metric_id", sa.Uuid(), nullable=True),
        sa.Column("raw_name", sa.Text(), nullable=False),
        sa.Column("value_numeric", sa.Numeric(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("value_canonical", sa.Numeric(), nullable=True),
        sa.Column("unit_canonical", sa.Text(), nullable=True),
        sa.Column("reference_low", sa.Numeric(), nullable=True),
        sa.Column("reference_high", sa.Numeric(), nullable=True),
        sa.Column("reference_text", sa.Text(), nullable=True),
        sa.Column("flag", sa.Text(), server_default="unknown", nullable=False),
        sa.Column("sample_type", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "flag IN ('low', 'normal', 'high', 'unknown')", name=op.f("ck_metrics_flag_valid")
        ),
        sa.CheckConstraint(
            "reference_low IS NULL OR reference_high IS NULL OR reference_low <= reference_high",
            name=op.f("ck_metrics_reference_range_ordered"),
        ),
        sa.CheckConstraint(
            "value_numeric IS NOT NULL OR value_text IS NOT NULL", name=op.f("ck_metrics_has_value")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_metric_id"],
            ["metric_dictionary.id"],
            name=op.f("fk_metrics_canonical_metric_id_metric_dictionary"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_metrics_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["report_id", "patient_id"],
            ["reports.id", "reports.patient_id"],
            name=op.f("fk_metrics_report_id_patient_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metrics")),
    )
    op.create_index(
        "ix_metrics_patient_id_canonical_metric_id_collected_at",
        "metrics",
        ["patient_id", "canonical_metric_id", "collected_at"],
        unique=False,
    )
    op.create_index("ix_metrics_report_id", "metrics", ["report_id"], unique=False)
    op.create_table(
        "report_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_report_chunks_chunk_index_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_report_chunks_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["report_id", "patient_id"],
            ["reports.id", "reports.patient_id"],
            name=op.f("fk_report_chunks_report_id_patient_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_chunks")),
        sa.UniqueConstraint(
            "report_id", "chunk_index", name=op.f("uq_report_chunks_report_id_chunk_index")
        ),
    )
    op.create_index(
        "ix_report_chunks_embedding_hnsw",
        "report_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index("ix_report_chunks_patient_id", "report_chunks", ["patient_id"], unique=False)
    op.create_table(
        "report_files",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_report_files_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_report_files")),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("report_files")
    op.drop_index("ix_report_chunks_patient_id", table_name="report_chunks")
    op.drop_index(
        "ix_report_chunks_embedding_hnsw",
        table_name="report_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("report_chunks")
    op.drop_index("ix_metrics_report_id", table_name="metrics")
    op.drop_index("ix_metrics_patient_id_canonical_metric_id_collected_at", table_name="metrics")
    op.drop_table("metrics")
    op.drop_index(op.f("ix_user_patient_access_patient_id"), table_name="user_patient_access")
    op.drop_table("user_patient_access")
    op.drop_index("ix_reports_patient_id_collected_at", table_name="reports")
    op.drop_table("reports")
    op.drop_table("users")
    op.drop_table("patients")
    op.drop_table("metric_dictionary")
    op.execute("DROP EXTENSION IF EXISTS vector")
